apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: py-github-artifactory-tekton 
  janus-idp.io/tekton: py-github-artifactory-tekton
  backstage.io/kubernetes-id: py-github-artifactory-tekton
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: py-github-artifactory-tekton
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml