apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: py-github-artifactory-tekton-gitops-repository
spec:
  url: https://github.com/RHTAP-RHDH/py-github-artifactory-tekton-gitops